fastlane_version "2.68.0"
default_platform :ios

generated_fastfile_id "8f5a1419-42ef-4050-a6ab-c40234bf20e8"

lane :codeSign do
  # create certificate 
   cert(
      username: "vahid.sheikhalizadeh@magna.com"
     )

   # create application provisions 
   sigh(
     force: true,
   username: "vahid.sheikhalizadeh@magna.com"
   )
  end

lane :build do
  increment_build_number
  # build your iOS app
  build_app(
   scheme: "fastLaneTest",
    export_method: "app-store"
  )
  gym
  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
  end