# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"
default_platform :ios
# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "8f5a1419-42ef-4050-a6ab-c40234bf20e8"



default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # increment_build_number

  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)
end

lane :codeSign do
  # create certificate 
   cert(
      username: "vahid.sheikhalizadeh@magna.com"
     )

   # create application provisions 
   sigh(
     force: true,
   username: "vahid.sheikhalizadeh@magna.com"
   )

  end

  lane :screenshots do
    capture_screenshots
    frame_screenshots(white: true)
  end